// Generated by https://quicktype.io

import { UsuarioDB } from "./UsuarioDB.inetrface";

export interface UserCreated {
    ok?:      boolean;
    usuario: UsuarioDB;
    token:   string;
    msg?:     string;
}