// Generated by https://quicktype.io

import { UsuarioDB } from "./UsuarioDB.inetrface";

export interface UserRenewGoogle {
    ok:        boolean;
    uid:       string;
    token:     string;
    usuarioDB: UsuarioDB;
}
